red:

  port: 5000
  auth:
      domain: red.n.uji.es
      users:
        - vrubert
        - borillo

  database:
    db_file: /data/db/red.db

  nginx:
    red_nginx_conf_file: /data/nginx/nginx.conf.d/red.conf
    socket: /var/run/docker.sock

  domain:
    name: uji.es
    dns_api: http://dns.uji.es/api
