red:
  webserver:
      host: haddock.si.uji.es
      port: 5002
      users:
        - vrubert
        - borillo

  database:
    filename: /data/db/red.db

  nginx:
    filename: /data/nginx.conf.d/red.conf
    hostname: nginx
    socket: /var/run/docker.sock
